version: '3.1'

services:

  db:
    image: postgres:14.0-alpine
    container_name: db
    ports:
      - "8080:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=db


volumes:
  volumedataholder:
  postgres_data:
    driver: local