version: '3.1'

services:
  springboot-api-demo:
    image: "licencjat:v1"
    build:
      context: .
    container_name: licencjat
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '5000:5000'
  db:
    image: postgres:14.0-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=db
    ports:
      - '5432:5432'
  frontend:
    image: "frontend:latest"
    container_name: frontend
    ports:
      - '3000:3000'
    depends_on:
      - springboot-api-demo
    stdin_open: true



volumes:
  volumedataholder:
  postgres_data:
    driver: local
